# Changes here will be overwritten by Copier
SelectCitation:
- AddCitationFile_flag
- AddCFFConvert_flag
SelectCodeQualityFeatures:
- AddLocalTests_flag
- SelectGitHubActions_flag
- AddLinting_flag
- AddSonarCloud_flag
- AddEditorConfig_flag
SelectCommunityFeatures:
- AddCodeConduct_flag
- AddContributing_flag
SelectDocumentationFeatures:
- AddLocalDocumentation_flag
- AddOnlineDocumentation_flag
- AddDevDoc_flag
- AddGitHubActionDocumentation_flag
SelectGitHubActions:
- AddGitHubActionBuild_flag
SelectPublishReleaseFeatures:
- SelectCitation_flag
- AddZenodo_flag
_commit: 0.6.1
_src_path: https://github.com/nlesc/python-template.git
code_of_conduct_email: s.b.szkudlarek@tudelft.nl
copyright_holder: Sacha Szkudlarek
email: s.b.szkudlarek@tudelft.nl
full_name: Sacha Szkudlarek
github_organization: szkuds
keywords: LBM, TUD, Delft University of Technology
license: Apachev2
package_name: tud_lbm
package_short_description: This is a lattice Boltzmann method package developed at
    Delft University of Technology.
template_profile: recommended
version: 0.0.1
