[simulation_type]
simulation_name = "Test chemical step simulation"
lattice_type = "D2Q9"
grid_shape = [
    201,
    101,
    1,
]
nt = 200
tau = 0.99
collision_scheme = "bgk"
init_type = "multiphase_bubbles"
type = "multiphase_hysteresis_chemical_step"

[boundary_conditions]
left = "periodic"
right = "periodic"
top = "bounce-back"
bottom = "wetting"
front = "periodic"
back = "periodic"

[chemical_step]
chemical_step_location = 0.5
chemical_step_edge = "bottom"
ca_advancing_pre_step = 120.0
ca_receding_pre_step = 100.0
ca_advancing_post_step = 70.0
ca_receding_post_step = 50.0

[gravity_masked_force]
force_g = 5e-06
inclination_angle_deg = 60

[hysteresis]
learning_rate = 0.05
max_iterations = 10

[initialisation]
centres = [
    [
        0.3,
        0,
    ],
]
radii = [
    0.3,
]
dispersed = "liquid"

[multiphase]
eos = "double-well"
kappa = 0.04
rho_l = 1.0
rho_v = 0.001
interface_width = 5

[output]
results_dir = "~/TUD_LBM_data/results"
save_fields = [
    "rho",
    "u",
]
plot_fields = [
    "density",
    "velocity",
]
output_format = "numpy"

